name: front_syndic
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  dio_cache_interceptor: ^3.5.0
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/launcher/icon_rec.png"

flutter_native_splash:
  color: "#3390E0"
  image: assets/launcher/launcher_rec.png
  android: true
  ios: true

flutter:
  assets:
    - assets/co_owner.svg
    - assets/location.svg
    - assets/close.svg
    - assets/arrow.svg
    - assets/tools.svg
    - assets/invoice.svg
    - assets/message.svg
  uses-material-design: true
