name: front_syndic
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl : ^0.19.0
  camera: ^0.11.0+2
  permission_handler: ^11.3.1
  path_provider: ^2.0.15
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  dio_cache_interceptor: ^3.5.0
  table_calendar: ^3.1.2
  flutter_bloc: ^8.0.0
  bloc : ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/co_owner.svg
    - assets/location.svg
    - assets/close.svg
    - assets/arrow.svg
  uses-material-design: true
